{
 "title": "POS-SYSTEM Backend",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "System load",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load_average_1m{group=\"pos-system\", job=\"pos-system-backend\"}"
    }
   ]
  },
  { "title": "Products list", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Products list AVG latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_sum{group=\"pos-system\", job=\"pos-system-backend\", method=\"GET\", uri=\"/api/v1/products\"}[1m])/increase(http_server_requests_seconds_count{group=\"pos-system\", job=\"pos-system-backend\", method=\"GET\", uri=\"/api/v1/products\"}[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Products list rate [rps]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{group=\"pos-system\", instance=\"172.16.31.1:8080\", job=\"pos-system-backend\", method=\"GET\", outcome=\"SUCCESS\", status=\"200\", uri=\"/api/v1/products\"}[1m])",
     "legendFormat": "200"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{group=\"pos-system\", instance=\"172.16.31.1:8080\", job=\"pos-system-backend\", method=\"GET\", outcome=\"SERVER_ERROR\", status=\"500\", uri=\"/api/v1/products\"}[1m])",
     "legendFormat": "500"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{group=\"pos-system\", instance=\"172.16.31.1:8080\", job=\"pos-system-backend\", method=\"GET\", outcome=\"SERVER_ERROR\", status=\"429\", uri=\"/api/v1/products\"}[1m])",
     "legendFormat": "500"
    }
   ]
  },
  { "title": "Orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Orders list AVG latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_sum{group=\"pos-system\", job=\"pos-system-backend\", method=\"GET\", uri=\"/api/v1/orders\"}[1m])/increase(http_server_requests_seconds_count{group=\"pos-system\", job=\"pos-system-backend\", method=\"GET\", uri=\"/api/v1/orders\"}[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Orders list rate [rps]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{group=\"pos-system\", job=\"pos-system-backend\", method=\"GET\", outcome=\"SUCCESS\", status=\"200\", uri=\"/api/v1/orders\"}[1m])",
     "legendFormat": "200"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{group=\"pos-system\", job=\"pos-system-backend\", method=\"GET\", outcome=\"SERVER_ERROR\", status=\"500\", uri=\"/api/v1/orders\"}[1m])",
     "legendFormat": "500"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{group=\"pos-system\", job=\"pos-system-backend\", method=\"GET\", outcome=\"SERVER_ERROR\", status=\"429\", uri=\"/api/v1/orders\"}[1m])",
     "legendFormat": "500"
    }
   ]
  },
  {
   "title": "Create order AVG latency [ms]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_sum{group=\"pos-system\", job=\"pos-system-backend\", method=\"POST\", uri=\"/api/v1/orders\"}[1m])/increase(http_server_requests_seconds_count{group=\"pos-system\", job=\"pos-system-backend\", method=\"POST\", uri=\"/api/v1/orders\"}[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Create order rate [rps]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{group=\"pos-system\", job=\"pos-system-backend\", method=\"POST\", outcome=\"SUCCESS\", status=\"200\", uri=\"/api/v1/orders\"}[1m])",
     "legendFormat": "200"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{group=\"pos-system\", job=\"pos-system-backend\", method=\"POST\", outcome=\"SERVER_ERROR\", status=\"500\", uri=\"/api/v1/orders\"}[1m])",
     "legendFormat": "500"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{group=\"pos-system\", job=\"pos-system-backend\", method=\"POST\", outcome=\"SERVER_ERROR\", status=\"429\", uri=\"/api/v1/orders\"}[1m])",
     "legendFormat": "500"
    }
   ]
  }
 ]
}