GET http://localhost:80/api/item?id=99
Accept: application/json

### Check user by username and password
POST http://localhost:8080/api/v1/users/validate
Accept: application/json

{
  "username": "admin@local.kz",
  "password": "123123"
}

### Get user by id
GET http://localhost:8080/api/v1/users/2
Accept: application/json

### Create user
POST http://localhost:8080/api/v1/users
Accept: application/json

{
  "username": "test@local.com",
  "email": "test@local.com",
  "password": "123123",
  "role": "USER"
}

### Change user password
POST http://localhost:8080/api/v1/users/1/change_password
Accept: application/json

{
  "id": 1,
  "password": "123123"
}

### Get user roles
GET http://localhost:8080/api/v1/dict/roles
Accept: application/json

### Get users
GET http://localhost:8080/api/v1/users?page=1
Accept: application/json

### Add category
POST http://localhost:8080/api/v1/dict/categories
Accept: application/json

{
  "name" : "test category1"
}

### Get category by id
GET http://localhost:8080/api/v1/dict/categories/7
Accept: application/json

### Get categories
GET http://localhost:8080/api/v1/dict/categories
Accept: application/json

### Add product
POST http://localhost:8080/api/v1/products
Accept: application/json

{
  "name": "Test product4112",
  "categoryId": 1,
  "description": "Test description",
  "purchasePrice": "1.0",
  "salePrice": "2.0",
  "stock": 100
}

### Get product by id
GET http://localhost:8080/api/v1/products/10
Accept: application/json

### Get products
GET http://localhost:8080/api/v1/products
Accept: application/json

### Create config
POST http://localhost:8080/api/v1/dict/configs

{
  "configKey": "TAX_PERCENT",
  "configValue": "5"
}

### Create order
POST http://localhost:8080/api/v1/orders
Accept: application/json

{
  "customerName": "SomeCustomer",
  "subtotal": "500.00",
  "tax": "25.00",
  "total": "525.00",
  "paid": "1000",
  "due": "475",
  "paymentType": "CREDIT",
  "created": "2022-02-25T22:29:26+00:00",
  "items": [
    {
      "productId": "1004",
      "quantity": "1"
    }
  ]
}

### Get order by id
GET http://localhost:8080/api/v1/orders/a3872e60-8618-4c05-aaf9-fb4dc01b1423

### Cancel order
DELETE http://localhost:8080/api/v1/orders/f78a8cdc-5f5f-4452-8f7c-6aba92e90ba6

### Generate invoice (SRANDARD)
POST http://localhost:8080/api/v1/orders/1000/invoice

### Generate invoice (THERMAL)
POST http://localhost:8080/api/v1/orders/f78a8cdc-5f5f-4452-8f7c-6aba92e90ba6/invoice?type=THERMAL

### Get payment types
GET http://localhost:8080/api/v1/dict/paymentTypes

### Start order processing
PUT http://localhost:8080/api/v1/orders/1231231/start

### Finish order processing
PUT http://localhost:8080/api/v1/orders/1231231/finish

### Get dashboard info
GET http://localhost:8080/api/v1/dashboard/info