GET http://localhost:80/api/item?id=99
Accept: application/json

### Check user by username and password
POST http://localhost:8080/api/v1/users/validate
Accept: application/json

{
  "username": "admin@local.kz",
  "password": "123123"
}

### Get user by id
GET http://localhost:8080/api/v1/users/2
Accept: application/json

### Create user
POST http://localhost:8080/api/v1/users
Accept: application/json

{
  "username": "test@local.com",
  "email": "test@local.com",
  "password": "123123",
  "role": "USER"
}

### Change user password
POST http://localhost:8080/api/v1/users/1/change_password
Accept: application/json

{
  "id": 1,
  "password": "123123"
}

### Get user roles
GET http://localhost:8080/api/v1/dict/roles
Accept: application/json

### Get users
GET http://localhost:8080/api/v1/users?page=1
Accept: application/json

### Get category by id
GET http://localhost:8080/api/v1/dict/categories/100
Accept: application/json