name: Build backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}-backend

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/pos-system-admin-java-quarkus
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: 'jdk'
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: backend-key-${{ steps.get-date.outputs.date }}
      - name: Checkout code
        uses: actions/checkout@v2          
      - name: Log in to the ghr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile, build Docker image and push to GHR
        run: |
          echo "BACKEND_VERSION=$(grep -m 1 "<version>.*</version>" pom.xml | awk -F '[><]' '{print $3}')" >> $GITHUB_ENV
          ./mvnw clean package \
            -Pnative \
            -DskipTests \
            -Dquarkus.native.additional-build-args='--initialize-at-build-time=java.awt.color.ColorSpace$BuiltInSpace' \
            -Dquarkus.container-image.build=true\
            -Dquarkus.container-image.group=\
            -Dquarkus.container-image.registry=ghcr.io\
            -Dquarkus.container-image.push=true\
            -Dquarkus.native.container-build=true \
            -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:22.0-java17 \
            -Dquarkus.native.native-image-xmx=6g \
            -Dquarkus.native.container-runtime-options='-m=8g'
      - name: Delete Local Artifacts From Cache
        shell: bash
        run: rm -r ~/.m2/repository/kz
