name: Build backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}-backend

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/pos-system-admin-java-quarkus
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: 'jdk'
      - name: Setup maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - name: Checkout code
        uses: actions/checkout@v2          
      - name: Log in to the ghr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compile, build Docker image and push to GHR
        run: |
          echo "BACKEND_VERSION=$(grep -m 1 "<version>.*</version>" pom.xml | awk -F '[><]' '{print $3}')" >> $GITHUB_ENV
          ./mvnw clean package \
            -Pnative \
            -DskipTests \
            -Dquarkus.native.additional-build-args='--initialize-at-build-time=java.awt.color.ColorSpace$BuiltInSpace' \
            -Dquarkus.container-image.build=true\
            -Dquarkus.container-image.group=\
            -Dquarkus.container-image.registry=ghcr.io\
            -Dquarkus.container-image.push=true\
            -Dquarkus.native.container-build=true \
            -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:22.0-java17 \
            -Dquarkus.native.native-image-xmx=6g \
            -Dquarkus.native.container-runtime-options='-m=8g'
