name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/pos-system-admin-java-quarkus
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: 'jdk'
      - name: Setup maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.2
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile and package backend
        run: |
          ./mvnw clean package \
            -Pnative \
            -DskipTests \
            -Dquarkus.native.additional-build-args='--initialize-at-build-time=java.awt.color.ColorSpace$BuiltInSpace' \
            -Dquarkus.native.container-build=true \
            -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:22.0-java17 \
            -Dquarkus.native.native-image-xmx=6g \
            -Dquarkus.native.container-runtime-options='-m=8g'
      - name: Log in to the ghr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: |
            ghcr.io/${{ github.repository }}-backend
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          context: backend/pos-system-admin-java-quarkus
          file: backend/pos-system-admin-java-quarkus/src/main/docker/Dockerfile.native
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
