name: Release Quarkus Backend

on:
  release:
    types: [created]
    
defaults:
  run:
    working-directory: ./backend/pos-system-admin-java-quarkus

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Get Date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
      shell: bash
    - name: Cache Maven Repository
      id: cache-maven
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        # refresh cache every month to avoid unlimited growth
        key: cache-${{ steps.get-date.outputs.date }}
    - name: Build with Maven
      run: |
        git config --global user.email "releasebot@example.com"
        git config --global user.name "ReleaseBot"
        TAG=${GITHUB_REF/refs\/tags\//}
        echo "Tag is $TAG"
        git pull
        
        # Remove existing tags (local and remote)
        git tag -d $TAG
        git push origin :refs/tags/$TAG
        # Update versions and push the changes
        mvn -B release:clean release:prepare release:perform
    - name: Delete Local Artifacts From Cache
      shell: bash
      run: rm -rf ~/.m2/repository/kz
#    - uses: eregon/publish-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        release_id: ${{ github.event.release.id }}
